In [66]:
import pandas as pd
import numpy as np

## Q1. Pandas version

What version of Pandas did you install?

In [67]:
pd.__version__

'3.0.5'

In [68]:
data = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

## Q2. Records count

How many records are in the dataset?

- 5000
- 9000
- 10000
- 15000

In [69]:
data.shape

(10000, 11)

## Q3. Fuel types

How many fuel types are presented in the dataset?

- 1
- 2
- 3
- 4

In [70]:
data.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [71]:
data['fuel_type'].nunique()

3

## Q4. Missing values

How many columns in the dataset have missing values?

- 0
- 1
- 2
- 3
- 4

In [72]:
data.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [73]:
(data.isna().sum()>0).sum()

np.int64(2)

## Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

- 21.2
- 31.2
- 41.2
- 51.2

-> ~21.2

In [74]:
data['fuel_efficiency_mpg'][data['origin']=='Asia'].max()

np.float64(41.2)

## Q6. Median value of horsepower

1. Find the median value of the `horsepower` column in the dataset.
2. Next, calculate the most frequent value of the same `horsepower` column.
3. Use the `fillna` method to fill the missing values in the `horsepower` column with the most frequent value from the previous step.
4. Now, calculate the median value of `horsepower` once again.

Has it changed?


- Yes, it increased
- Yes, it decreased
- No

In [75]:
median=data['horsepower'].median()
median

np.float64(254.0)

In [76]:
mode=data['horsepower'].mode()[0]
mode

np.float64(252.0)

In [77]:
data['horsepower'].fillna(mode).median()

np.float64(252.0)

## Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson.

- 0.0369
- 0.369
- 3.69
- 36.9

In [78]:
data_asia=data[data['origin']=="Asia"][['vehicle_weight','model_year']].head(7)

In [79]:
data_asia

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [80]:
X=data_asia.values
XTX=X.T.dot(X)
XTX_inv=np.linalg.inv(XTX)
print(XTX)
print(XTX_inv)

[[131950500  60750580]
 [ 60750580  28041424]]
[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

In [81]:
y=[1100, 1300, 800, 900, 1000, 1100, 1200]

In [82]:
w = (XTX_inv @ X.T) @ y
w

array([0.13644777, 0.2327492 ])

In [83]:
sum(w)

np.float64(0.36919696904925486)